[theme]
base = "light"
primaryColor = "#c8102e"
backgroundColor = "#f3f5f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#1b2433"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
